# 220117 python 다섯번째 수업: 클래스, 모듈, 패키지, * Numpy *

### 1. 클래스
클래스를 사용하지 않아도 구동할 수 있는 경우도 많다  
필수적이지는 않지만 적재적소에 잘 사용하면 더 편리하게 사용할 수 있음  
일단은 개념적인 이해를 선행하도록하자

In [1]:
# 클래스의 필요성

result = 0
def add(num):
    #괄호 안의 숫자가 들어오면 더해주게 만들기
    global result
    result += num
    return result

In [2]:
print(add(3))
print(add(4))

3
7


In [4]:
# 클래스

# 두 개의 계산기로 사용하기 위해서는 두 개의 함수가 필요하다
# 그때마다 추가하면 너무 번거롭지않을까?

result1 = 0
result2 = 0

def add1(num):
    #괄호 안의 숫자가 들어오면 더해주게 만들기
    global result1
    result1 += num
    return result1

def add2(num):
    #괄호 안의 숫자가 들어오면 더해주게 만들기
    global result2
    result2 += num
    return result2

In [5]:
print(add1(3))
print(add1(4))
print(add2(5))
print(add2(6))

3
7
5
11


In [6]:
# 클래스 만들어보기
class Calculator:
    def __init__(self):
        self.result = 0 # 초기값을 주기
        #클래스 안에 있으니까 시작 값이 늘 0이 된다.
    def add(self, num):
        self.result += num
        return self.result
    

In [11]:
# 클래스 호출하기
cal1 = Calculator()

In [12]:
print(cal1.add(3)) #syntax: 변수.함수
print(cal1.add(4))
#예: a.upper() 이렇게

3
7


In [13]:
# 초기화하고싶다면? 다른 변수로 새롭게 불러오면 된다.
cal2 = Calculator()

In [14]:
print(cal2.add(5)) #syntax: 변수.함수
print(cal2.add(6))

5
11


반복적인 함수를 만들어줄 때 클래스를 만들어준다.

## 2. 모듈
클래스보다 상위개념   
클래스, 함수, 외장함수(함수를 불러와야사용할 수 있음), 내장함수(바로 사용가능한 함수)  


In [15]:
import os
#사용할 수 있는 함수, 클래스 등이 모아져있음
#import하여 사용함

######syntax######
# from collections import ___: from 모듈이름 import 모듈 안 함수이름
# sys.bulletin_module_names: 모듈이름.모듈 안 함수 이름

## 3. 패키지
모듈보다 상위개념(지금까지 가장 상위의 개념)  
계층적으로 모듈, 클래스, 함수, 변수가 들어있는 경우  
.을 사용함. numpy, pandas 등을 패키지라고 함   

## 4. 예외처리
오류를 어떻게 핸들링할 것인가?  
오류를 문제없이 넘어가기 위해

In [16]:
# 대표적인 오류들
f = open('없는 파일', 'r')
# FileNotFoundError

FileNotFoundError: [Errno 2] No such file or directory: '없는 파일'

In [17]:
# ZeroDivisionError
4 / 0

ZeroDivisionError: division by zero

In [18]:
# IndexError 
a = [1, 2, 3]
a[3]

IndexError: list index out of range

In [19]:
# 에러 그냥 넘어가게 하려면?
a = [1, 2, 3]
print(a[0])
print(a[3])# 오류 발생 전까지는 실행됨
print(a[1])

1


IndexError: list index out of range

In [23]:
#예외처리 frame
try:
    a = [1, 2, 3]
    b = [0, 3, 1]
    for i in b:
        print(a[i])
        #a[3]일 때 오류가 생길 것이므로 에러가 발생할 때 해결하는 틀
#모든 에러가 발생해도 넘어가기
#except:
# 에러 이름을 알 때
except IndexError as e:
    print(e)

1
list index out of range


In [24]:
#예외처리 frame
try:
    a = [1, 2, 3]
    print(a[0])
    print(a[3])
    print(a[1])
        #a[3]일 때 오류가 생길 것이므로 에러가 발생할 때 해결하는 틀
# 에러 이름을 알 때
except IndexError as e:
    print(e)

1
list index out of range


In [25]:
a = [1, 2, 3]
print(a[0])
# 에러가 날 부분만 try except사용해 오류를 회피해준다.
try:
    print(a[3])
        #a[3]일 때 오류가 생길 것이므로 에러가 발생할 때 해결하는 틀
# 에러 이름을 알 때
except IndexError as e:
    print(e)
print(a[1])

1
list index out of range
2


In [26]:
#zerodivisionerror
try: 
    4 / 0
except ZeroDivisionError as e:
    print(e)

division by zero


In [28]:
# 여러 개의 오류 발생하는 경우?
try:
    a = [1, 2, 3]
    print(a[3])
    4 / 0
except IndexError:
    print("인덱스 번호를 확인하세요.")
except ZeroDivisionError:
    print("0으로는 나눌 수 없습니다.")
# 출력은 indexerror만 출력됨. 먼저 발생하는 오류만 except구문이 작동. 
# 에러 발생하면 구문이 멈추기 때문에

인덱스 번호를 확인하세요.


In [29]:
# 여러 개의 오류 발생하는 경우?
try:
    4 / 0 #어떤 오류가 먼저 발생하였는가
    a = [1, 2, 3]
    print(a[3])
except IndexError:
    print("인덱스 번호를 확인하세요.")
except ZeroDivisionError:
    print("0으로는 나눌 수 없습니다.")
# 출력은 indexerror만 출력됨. 먼저 발생하는 오류만 except구문이 작동. 
# 에러 발생하면 구문이 멈추기 때문에

0으로는 나눌 수 없습니다.


In [30]:
# 여러 개의 오류 발생하는 경우?
try:
    a = [1, 2, 3]
    print(a[3])
    4 / 0
except (IndexError, ZeroDivisionError) as e:
    print(e)
# 출력은 index error만 출력됨. 먼저 발생하는 오류만 except구문이 작동. 
# 에러 발생하면 구문이 멈추기 때문에

list index out of range


In [31]:
# 오류를 그냥 넘어가게 해주고 싶다면?
a = [1, 2, 3]
print(a[0])
# 에러가 날 부분만 try except사용해 오류를 회피해준다.
try:
    print(a[3])
        #a[3]일 때 오류가 생길 것이므로 에러가 발생할 때 해결하는 틀
# 에러 이름을 알 때
except IndexError:
    pass
print(a[1])

#오류가 발생하면 구문이 멈추기 때문에 계속 내용을 진행시킬 수 없음. 
#새로이 뭔갈 넣어주어야 할 것 같네

1
2


In [34]:
try: 
    a = [1, 2, 3]
    b = [0, 3, 1]
    for i in b:
        print(a[i])
except IndexError as e:
    print(e)

1
list index out of range


In [36]:
for i in range(1, 10, 3): #start, stop+1, step
    print(i)

1
4
7


In [37]:
a = ['navy', 'salmon', 'yellow']
' '.join(a) #리스트도 join함수 사용가능하다

'navy salmon yellow'

# Numpy
아나콘다 설치 시 자동으로 설치  
불러와서 사용하는 방법, 생성하는 방법  
### 1) numpy 배열만들기
행렬을 만들어서 수학연산을 직접 해줄 필요가 있을 때 사용  
결측치 작업할 때 사용     

In [38]:
# 불러오기
import numpy as np # 불러올 때 길면 복잡하니까 약자로 불러옴
import pandas as pd

In [40]:
# array만들기
num = np.array(range(1, 11))
num #겉보기에는 list와 유사해보인다

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
array1 = np.array([1, 2, 'a', 'b'])
array1 
# 숫자가 문자로 바뀜. 문자열로 array를 만들면 datatype이 <U11이 된다
# 문자열로 자동변환

array(['1', '2', 'a', 'b'], dtype='<U11')

In [42]:
# 배열을 만들어주는 함수

ones = np.ones([2, 4]) #1로만 이루어진 2행 4열
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
ones1 = np.ones(10) #1차원 array
ones1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
# 0으로만 이루어진 행렬을 만들고 싶다
zeros = np.zeros([2, 4])
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
zeros.shape # 배열이 어떻게 구성되어있는지 출력

(2, 4)

In [47]:
zeros.ndim # 배열의 차원(행의 수)

2

In [48]:
# 어떤 데이터타입으로 구성되어있는지 궁금하다
zeros.dtype #float

dtype('float64')

In [50]:
# 간편하게 동일한 모양으로
np_nums = np.arange(1, 10)
np_nums

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# step
np_nums = np.arange(1, 10, 0.25)
np_nums

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [55]:
#소수점은 버리고싶다
np_nums = np.arange(1, 10, 0.25).astype(int) #정수형
np_nums

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9])

### 2) 행렬전환

In [63]:
sap = np.array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'])
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [64]:
sap.shape #1차원 배열

(8,)

In [62]:
sap1d = sap.T # 왜? 전치해도 똑같지?
sap1d.shape

(8,)

In [58]:
sap2d = sap.reshape(2, 4)
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [59]:
sap3d = sap.reshape(2, 2, 2)
sap3d # 두 개의 2차원 행렬이 나눠지면서 3차원이 됨

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [60]:
# 행렬 전치가 필요할 때
sap2d.T #4행 2열짜리 행렬이 됨

array([['MMM', 'ACE'],
       ['ABT', 'ATVI'],
       ['ABBV', 'ADBE'],
       ['ACN', 'ADT']], dtype='<U4')

In [65]:
sap3d.transpose((0, 2, 1)) #3차원 배열에 대한 이해가 필요하다

array([[['MMM', 'ABBV'],
        ['ABT', 'ACN']],

       [['ACE', 'ADBE'],
        ['ATVI', 'ADT']]], dtype='<U4')

In [66]:
ar1 = np.arange(1, 10)
ar1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
ar1.reshape([2, 4]) #reshape개수가 맞지않는다

ValueError: cannot reshape array of size 9 into shape (2,4)

In [70]:
# 인덱싱과 슬라이싱
# 리스트 안에 조건 넣어서 해보는거
dirty = np.array([9, 4, 1, -0.01, -0.001])
dirty
# array([ 9.e+00,  4.e+00,  1.e+00, -1.e-02, -1.e-03(e의 -3승)])

array([ 9.e+00,  4.e+00,  1.e+00, -1.e-02, -1.e-03])

In [72]:
w_dirty = dirty < 0
w_dirty #true인 값이 음수

array([False, False, False,  True,  True])

In [74]:
dirty[w_dirty] = 0
#dirty[dirty < 0] #bool인덱스 사용
# 0보다 작은 값들만 0으로 바꾸어준다
dirty

array([9., 4., 1., 0., 0.])

In [75]:
linear = np.arange(-1, 1, 0.2)
linear

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01])

In [77]:
(linear <= 0.5) & (linear >= -0.5)

array([False, False, False,  True,  True,  True,  True,  True, False,
       False])

#### and => &
#### or => |
#### not => -

In [78]:
linear[(linear <= 0.5) & (linear >= -0.5)] # 슬라이싱

array([-4.00000000e-01, -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,
        4.00000000e-01])

In [79]:
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [80]:
#스마트 인덱싱
sap[[1, 2, -1]] # 원하는 것만

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [91]:
l_sap = list(sap)
l_sap

['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT']

In [92]:
[l_sap[1], l_sap[2], l_sap[-1]] #이렇게 하면 어려우니까 스마트 인덱싱을 활용함

['ABT', 'ABBV', 'ADT']

In [82]:
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [81]:
#스마트 슬라이싱

sap2d[:, [1]] #전체 행 중 두번째 열만
#2차원 행렬

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [85]:
#스마트 슬라이싱

sap2d[:, [1]].ndim #전체 행 중 두번째 열만
#2차원 행렬

2

In [84]:
sap2d[:, 1] # 출력된 모양이 다르다
#1차원 행렬

array(['ABT', 'ATVI'], dtype='<U4')

In [86]:
sap2d[:, 1].ndim # 출력된 모양이 다르다
#1차원 행렬

1

In [88]:
sap2d[[1], [1]] #1 행 1열의 요소만 반환
#2차원 행렬

array(['ATVI'], dtype='<U4')

In [4]:
import numpy as np
array2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array2d[0:2,1:2] #2차원일 때는 이렇게 해도 충분하다

array([[2],
       [5]])

In [6]:
array2d[0:2, 0:2] #다른 슬라이싱과 마찬가지로 end+1이 출력된다

array([[1, 2],
       [4, 5]])

In [7]:
# 브로드캐스팅
# 리스트와의 차이와 함께 살펴보기
a = [1, 2, 3]
b = [4, 5, 6]

a + b

[1, 2, 3, 4, 5, 6]

In [100]:
#각 요소들을 더하고 싶다면?
#즉, 배열에서 벡터의 연산을 하고싶다
#리스트에서는 하나의 요소씩 더해줘야한다.
for i in a:
    for j in b:
        j+i

'for i in a:\n    for j in b:'

In [101]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#배열끼리의 사칙연산이 가능해진다.
a + b

array([5, 7, 9])

In [102]:
#곱하기
a = [1, 2, 3]
a * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [103]:
a = np.array([1, 2, 3])
a * 5 #각 자리의 연산이 필요하다 할 때 np.array사용해주면 된다.

array([ 5, 10, 15])

In [104]:
np.eye(4) #대각행렬 만들어주는 함수

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [107]:
noise = np.eye(4) + 0.01 * np.ones((4, )) # 모든 행렬에 0.01 더해주는 것
# 0.01 * np.ones((4, ))
noise

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [105]:
0.01 * np.ones((4, ))

array([0.01, 0.01, 0.01, 0.01])

In [108]:
#랜덤으로 노이즈를 넣어주고 싶다
noise = np.eye(4) + 0.01 * np.random.random((4, 4)) # 모든 행렬에 0.01 더해주는 것
# 0.01 * np.ones((4, ))
noise

array([[1.00273293e+00, 1.66365626e-04, 4.26882375e-03, 9.22039716e-03],
       [9.83491909e-03, 1.00924700e+00, 2.96549952e-03, 5.57734733e-03],
       [9.62003490e-05, 5.96847200e-03, 1.00866951e+00, 9.10315542e-03],
       [4.84039608e-03, 4.80561871e-03, 1.60205933e-03, 1.00507080e+00]])

In [109]:
0.01 * np.random.random((4, 4))

array([[0.00700061, 0.00320276, 0.0006822 , 0.0070894 ],
       [0.00819439, 0.00309791, 0.00856566, 0.00250959],
       [0.00369688, 0.0090817 , 0.00464674, 0.00841282],
       [0.00743226, 0.00270368, 0.00845857, 0.00716833]])

In [110]:
noise = np.eye(4) + 0.01 * np.random.random((4, 4)) # 모든 행렬에 0.01 더해주는 것
# 0.01 * np.ones((4, ))
np.round(noise, 2)

array([[1.01, 0.  , 0.  , 0.  ],
       [0.  , 1.01, 0.01, 0.01],
       [0.  , 0.  , 1.  , 0.01],
       [0.01, 0.01, 0.  , 1.  ]])

round함수는 universal함수.    
#### 유니버셜 함수란?
"연산을 해줄 수 있는 함수들"   
- 사칙연산: add, multiply, negative, exp, log, sqrt
- 삼각함수: sin, cos, hypot
- 비트 단위: bitwise_and, left_shift
- 관계형, 논리: less, logical_not, equal
- 최대/최소: maximum, minimum
- 부동소수점: isinf, infinite, isnan

In [8]:
stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2, 40.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2, 30.22, 30.91])
stocks

array([140.49,   0.97,  40.68,  41.53,  55.7 ,  57.21,  98.2 ,  40.49,
         0.97,  40.68,  41.53,  55.7 ,  57.21,  98.2 ,  30.22,  30.91])

In [9]:
#주말동안 어떤 주식이 떨어졌는지

stocks = stocks.reshape(8, 2).T
stocks

array([[140.49,  40.68,  55.7 ,  98.2 ,   0.97,  41.53,  57.21,  30.22],
       [  0.97,  41.53,  57.21,  40.49,  40.68,  55.7 ,  98.2 ,  30.91]])

In [11]:
stocks[0][2]

55.7

In [14]:
stocks[0][1:4]

array([40.68, 55.7 , 98.2 ])

In [118]:
fall = np.greater(stocks[0], stocks[1]) #전, 후(행 기준) # 떨어진 것만 포함

In [119]:
sap[fall] #sap에 적용
#주가의 전 후 비교. 떨어진 주식만 뽑아줌

array(['MMM', 'ACN', 'ATVI', 'ADT'], dtype='<U4')

In [120]:
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [128]:
rise = np.greater(stocks[1], stocks[0])
rise
# 주가가 오른 것들만 true

array([False,  True,  True, False,  True, False,  True, False])

In [129]:
sap[rise] # bool인덱스를 하는 것
# 주가가 오른 종목만 표기됨

array(['ABT', 'ABBV', 'ACE', 'ADBE'], dtype='<U4')

In [133]:
changes = np.where(np.abs(stocks[1] - stocks[0])>20.00, stocks[1] - stocks[0], 0) #전후가격을 빼줌
#abs: 절댓값
#true, false 판단 후에 어떤걸 값으로 할건지 작성
#다른 연산까지 한번에 하고 싶을 때
changes

#부가설명
"""Docstring:
where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`."""

array([-99.81,  42.5 ,  40.56, -26.99,  40.56,   0.  ,   0.  , -67.29])

In [136]:
sap[np.nonzero(changes)]

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ADT'], dtype='<U4')

In [135]:
np.nonzero(changes)

(array([0, 1, 2, 3, 4, 7], dtype=int64),)

In [137]:
sap[stocks[1] - stocks[0]>20.00]

array(['ABT', 'ABBV', 'ACE'], dtype='<U4')

숙제: 내장함수, 외장함수 자습하기